### ISSUE TITLE
Re-installed Hap now getting mdns error

### ISSUE THREAD

**Issue by Techchunky** [KhaosT/HAP-NodeJS#184]
I am getting this error after I re-installed HAP-NodeJS

/home/pi/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:424:18)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/home/pi/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)

**Comment by KhaosT** [comment]
Are you sure you installed hap-nodejs correctly? the place of mdns module (/home/pi/node_modules/mdns) is strange...

**Comment by Techchunky** [comment]
I installed Hap-NodeJs in /home/pi

**Comment by KhaosT** [comment]
have you try ``npm rebuild``?

**Comment by Techchunky** [comment]
yes @KhaosT

**Comment by KhaosT** [comment]
interesting... maybe try remove ``/home/pi/node_modules/`` and then npm install again?

**Comment by Techchunky** [comment]
I Did npm install mdns, it reinstalled it. 

Now I get this error:

 return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:424:18)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at new require (internal/module.js:13:17)
    at Object.<anonymous> (/home/pi/node_modules/srp/node_modules/bignum/index.js:4:14)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)

@KhaosT

**Comment by KhaosT** [comment]
@Techchunky are you sure ``npm install`` succeeded without producing any error?

**Comment by Techchunky** [comment]
Yes @KhaosT

**Comment by KhaosT** [comment]
wait... so you did ``npm install mdns`` instead of ``npm install`` at /home/pi/?

**Comment by Techchunky** [comment]
I did both, now I get : 

 throw err;
    ^

Error: Cannot find module '/home/pi/HAP-NodeJS/Core,js'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3

@KhaosT

**Comment by Techchunky** [comment]
Yes @KhaosT

**Comment by KhaosT** [comment]
I thought you installed hap-nodejs at /home/pi/ instead of /home/pi/HAP-NodeJS/

let's start from scratch. Can you run the following line by line in terminal?
``
cd /home/pi
rm -rf /home/pi/HAP-NodeJS
rm -rf /home/pi/node_modules/
npm install hap-nodejs
cd /home/pi/node_modules/HAP-NodeJS
node Core.js
``

**Comment by Techchunky** [comment]
should I run this command in home/pi ? @KhaosT

**Comment by KhaosT** [comment]
it doesn't matter, the first line makes sure you're at /home/pi ...

**Comment by Techchunky** [comment]
Awesome This works, Also the other issue I had is now solved #180 . I also see outputs on terminal when connecting to the light this wasn't the case. I think this problem occurred because I installed from git clone and not from npm! Again Thank you!!  @KhaosT

**Comment by Techchunky** [comment]
Awesome This works, Also the other issue I had is now solved #180 . I also see outputs on terminal when connecting to the light this wasn't the case. I think this problem occurred because I installed from git clone and not from npm! Again Thank you!! @KhaosT

**Comment by fpereiracostaa** [comment]
any ideia how to start hap-nodejs with startup on raspberry usign this npm install?
