### ISSUE TITLE
Could not add accessory

### ISSUE THREAD

**Issue by anal-probe** [KhaosT/HAP-NodeJS#202]
After today's git pull I'm unable to add any accessory on my iphone. It show the list of devices, but after entering pin error happens. I can see the following error in log-file:

```
TypeError: this._advertisement.updateTXTRecord is not a function
    at Advertiser.updateAdvertisement (/home/pi/HAP-NodeJS/lib/Advertiser.js:68:25)
    at Accessory._handlePair (/home/pi/HAP-NodeJS/lib/Accessory.js:460:20)
    at emitThree (events.js:97:13)
    at HAPServer.emit (events.js:175:7)
    at HAPServer._handlePairStepFive (/home/pi/HAP-NodeJS/lib/HAPServer.js:407:8)
    at HAPServer._handlePairStepFour (/home/pi/HAP-NodeJS/lib/HAPServer.js:376:8)
    at HAPServer._handlePairStepThree (/home/pi/HAP-NodeJS/lib/HAPServer.js:350:8)
    at HAPServer._handlePair (/home/pi/HAP-NodeJS/lib/HAPServer.js:252:10)
    at HAPServer.<anonymous> (/home/pi/HAP-NodeJS/lib/HAPServer.js:178:39)
    at emitNone (events.js:67:13)
```

**Comment by KhaosT** [comment]
You need to run npm install to update dependent package

**Comment by anal-probe** [comment]
Thanks, that solve problem
