### ISSUE TITLE
Failed to start the server for the first time

### ISSUE THREAD

**Issue by kaosrq** [KhaosT/HAP-NodeJS#230]
When starting the server throws me the following message:

```
root@raspberrypi:/home/pi/HAP-NodeJS# npm rebuild
root@raspberrypi:/home/pi/HAP-NodeJS# node Core.js
module.js:339
    throw err;
    ^

Error: Cannot find module 'node-persist'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/HAP-NodeJS/Core.js:2:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)

```

**Comment by KhaosT** [comment]
Make sure you run ``npm install`` before start the server

Best Wishes,
Tian Zhang

**Comment by kaosrq** [comment]
thanks, that solved my problem.

**Comment by legotheboss** [comment]
@KhaosT you can close this
