### ISSUE TITLE
npm install race condition

### ISSUE THREAD

**Issue by dodekeract** [KhaosT/HAP-NodeJS#242]
## Description

When using `hap-nodejs` via `npm` I discovered that it actually mattered in what order the packages `hap-nodejs` and `node-persist@0.0.8` are installed.

When I initially attempted to use this library, I looked at the `BridgedCore.js` example. Then I installed the needed packages and tried to refactor the code, so that it uses the npm dependencies.

I encountered a lot of problems related to `localStorage` being `undefined`. This is **because of a hack**, this library relies on. It trusts `node-persist` to be the same instance on the library & `BridgedCore.js` files. However, when you install `hap-nodejs` first, npm will install two instances of `node-persist`, which breaks the `localStorage`.

### a) install `hap-nodejs` first

This reliably fails on both of my systems, since `npm` will install two instances of `node-persist`.

#### Console Output

````
HAP-NodeJS starting...
/home/dodekeract/code/HAP-NodeJS/node_modules/hap-nodejs/node_modules/node-persist/node-persist.js:107
        return localStorage.getItem(key, callback);
                           ^

TypeError: Cannot read property 'getItem' of undefined
    at Object.nodePersist.getItem (/home/dodekeract/code/HAP-NodeJS/node_modules/hap-nodejs/node_modules/node-persist/node-persist.js:107:28)
    at Function.AccessoryInfo.load (/home/dodekeract/code/HAP-NodeJS/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:103:23)
    at Bridge.Accessory.publish (/home/dodekeract/code/HAP-NodeJS/node_modules/hap-nodejs/lib/Accessory.js:417:39)
    at Object.<anonymous> (/home/dodekeract/code/HAP-NodeJS/BridgedCore.js:25:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
````

#### `npm list`

````
hap-nodejs-bug@1.0.0 /home/dodekeract/code/HAP-NodeJS
├─┬ hap-nodejs@0.3.2
│ ├─┬ curve25519@1.1.0 (git://github.com/KhaosT/node-curve25519.git#922eae612bb379fa84e8deb29f80c53d57c8be7b)
│ │ ├── bindings@1.2.1
│ │ └── nan@2.3.2
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ ed25519@0.0.3 (git://github.com/KhaosT/ed25519.git#6356bc9e6e4643d56020293c14920ac12bcaa1ac)
│ │ ├── bindings@1.2.1
│ │ └── nan@2.3.2
│ ├─┬ mdns@2.3.2
│ │ ├── bindings@1.2.1
│ │ └── nan@2.2.1
│ ├─┬ node-persist@0.0.8
│ │ ├── mkdirp@0.3.5
│ │ └── q@1.1.2
│ └─┬ srp@0.2.0 (git://github.com/KhaosT/node-srp.git#7feff53254897a0b1b9f0667ad17a8beb78acbb9)
│   └─┬ bignum@0.11.0
│     └── nan@2.3.2
└─┬ node-persist@0.0.8
  ├── mkdirp@0.3.5
  └── q@1.1.2
````

Two separate instances of `node-persist`.

### b) install `node-persist@0.0.8` first

This fixed the issue, since only one instance of `node-persist` will be installed. Took me about 4 hours to figure this one out though.

#### Console Output

````
HAP-NodeJS starting...
````

#### `npm list`

````
hap-nodejs-bug@1.0.0 /home/dodekeract/code/HAP-NodeJS
├─┬ hap-nodejs@0.3.2
│ ├─┬ curve25519@1.1.0 (git://github.com/KhaosT/node-curve25519.git#922eae612bb379fa84e8deb29f80c53d57c8be7b)
│ │ ├── bindings@1.2.1
│ │ └── nan@2.3.2
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├─┬ ed25519@0.0.3 (git://github.com/KhaosT/ed25519.git#6356bc9e6e4643d56020293c14920ac12bcaa1ac)
│ │ ├── bindings@1.2.1
│ │ └── nan@2.3.2
│ ├─┬ mdns@2.3.2
│ │ ├── bindings@1.2.1
│ │ └── nan@2.2.1
│ └─┬ srp@0.2.0 (git://github.com/KhaosT/node-srp.git#7feff53254897a0b1b9f0667ad17a8beb78acbb9)
│   └─┬ bignum@0.11.0
│     └── nan@2.3.2
└─┬ node-persist@0.0.8
  ├── mkdirp@0.3.5
  └── q@1.1.2
````

As you can see, there is only one instance of `node-persist`.

## Code To Reproduce This

**BridgedCore.js (modified)**

````javascript
var path = require('path');
var storage = require('node-persist');
var uuid = require('hap-nodejs').uuid;
var Bridge = require('hap-nodejs').Bridge;
var Accessory = require('hap-nodejs').Accessory;

console.log("HAP-NodeJS starting...");

// Initialize our storage system
storage.initSync();

// Start by creating our Bridge which will host all loaded Accessories
var bridge = new Bridge('Node Bridge', uuid.generate("Node Bridge"));

// Listen for bridge identification event
bridge.on('identify', function(paired, callback) {
  console.log("Node Bridge identify");
  callback(); // success
});

bridge.addBridgedAccessory(require('./Light_accessory.js').accessory);

// Publish the Bridge on the local network.
bridge.publish({
  username: "CC:22:3D:E3:CE:F6",
  port: 51826,
  pincode: "031-45-154",
  category: Accessory.Categories.BRIDGE
});
````

**Light_accessory.js (modified)**

````javascript
var Accessory = require('hap-nodejs').Accessory;
var Service = require('hap-nodejs').Service;
var Characteristic = require('hap-nodejs').Characteristic;
var uuid = require('hap-nodejs').uuid;

// here's a fake hardware device that we'll expose to HomeKit
var FAKE_LIGHT = {
  powerOn: false,
  brightness: 100, // percentage

  setPowerOn: function(on) {
    console.log("Turning the light %s!", on ? "on" : "off");
    FAKE_LIGHT.powerOn = on;
  },
  setBrightness: function(brightness) {
    console.log("Setting light brightness to %s", brightness);
    FAKE_LIGHT.brightness = brightness;
  },
  identify: function() {
    console.log("Identify the light!");
  }
}

// Generate a consistent UUID for our light Accessory that will remain the same even when
// restarting our server. We use the `uuid.generate` helper function to create a deterministic
// UUID based on an arbitrary "namespace" and the word "light".
var lightUUID = uuid.generate('hap-nodejs:accessories:light');

// This is the Accessory that we'll return to HAP-NodeJS that represents our fake light.
var light = exports.accessory = new Accessory('Light', lightUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
light.username = "1A:2B:3C:4D:5E:FF";
light.pincode = "031-45-154";

// set some basic properties (these values are arbitrary and setting them is optional)
light
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "Oltica")
  .setCharacteristic(Characteristic.Model, "Rev-1")
  .setCharacteristic(Characteristic.SerialNumber, "A1S2NASF88EW");

// listen for the "identify" event for this Accessory
light.on('identify', function(paired, callback) {
  FAKE_LIGHT.identify();
  callback(); // success
});

// Add the actual Lightbulb Service and listen for change events from iOS.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKitTypes.js`
light
  .addService(Service.Lightbulb, "Fake Light") // services exposed to the user should have "names" like "Fake Light" for us
  .getCharacteristic(Characteristic.On)
  .on('set', function(value, callback) {
    FAKE_LIGHT.setPowerOn(value);
    callback(); // Our fake Light is synchronous - this value has been successfully set
  });

// We want to intercept requests for our current power state so we can query the hardware itself instead of
// allowing HAP-NodeJS to return the cached Characteristic.value.
light
  .getService(Service.Lightbulb)
  .getCharacteristic(Characteristic.On)
  .on('get', function(callback) {

    // this event is emitted when you ask Siri directly whether your light is on or not. you might query
    // the light hardware itself to find this out, then call the callback. But if you take longer than a
    // few seconds to respond, Siri will give up.

    var err = null; // in case there were any problems

    if (FAKE_LIGHT.powerOn) {
      console.log("Are we on? Yes.");
      callback(err, true);
    }
    else {
      console.log("Are we on? No.");
      callback(err, false);
    }
  });

// also add an "optional" Characteristic for Brightness
light
  .getService(Service.Lightbulb)
  .addCharacteristic(Characteristic.Brightness)
  .on('get', function(callback) {
    callback(null, FAKE_LIGHT.brightness);
  })
  .on('set', function(value, callback) {
    FAKE_LIGHT.setBrightness(value);
    callback();
  })
````

## Proposed Solution

Since relying on only having one instance of `node-persist` is apparently error-prone, I suggest to just allow users to pass in any storage solution they want to pass into this library. At least allow passing an instance of `node-persist` to have a reliable way to fix this issue.

## Versions

**npm**: 2.15.1
**node**: 4.4.3
**hap-nodejs**: 0.3.2
**node-persist**: 0.0.8
**OS**: Ubuntu 16.04 & Raspbian Jessie

**Comment by KhaosT** [comment]
This is not a bug with the project, instead, it's how node.js lookup external modules. If you plan to use hap-nodejs in a separate project, please add hap-nodejs as a dependency of the project and use npm or other package manager to manage the modules.

**Comment by dodekeract** [comment]
Did you even read it? I AM using npm. What? This IS caused by this module not allowing to pass the node-persist instance.

**Comment by KhaosT** [comment]
@dodekeract I don't get it, if your dependency is managed by npm, how you can ``a) install hap-nodejs first`` or ``b) install node-persist@0.0.8 first``? npm doesn't give you the option to do this. homebridge has been using this package as a dependency for ages and it never encounter this problem.

**Comment by KhaosT** [comment]
@dodekeract and if you want, [here](https://dl.dropbox.com/s/tqkpyko7bs7lff8/repro.zip) is the sample test I created trying to reproduce this problem. After ``npm install`` it runs fine.

**Comment by dodekeract** [comment]
@KhaosT yes, npm does `npm install a && npm install b`.

**Comment by KhaosT** [comment]
@dodekeract but that's not what I mean by "manage dependency" ... ideally by using ``package.json``, npm will recursively figure out what package is needed and install all things in the right place. If you manually install each package via npm, then due to the way how npm look up the existing packages, there might have a issue. However, I'm not sure in that case the issue belongs to this project or npm itself.

**Comment by dodekeract** [comment]
@KhaosT at least in my usual workflow (I added this to an existing project) I use npm install package --save. This will probably work on when somebody uses a fresh install of my project's repo, but it's REALLY confusing when you're trying to use a new package in a new project. From the installation order, it even makes sense to install hap first (if you're not aware of this bug).

It's like really confusing if everything breaks, just because you installed it in the wrong order when trying to include HAP in a project.

**Comment by underbluewaters** [comment]
I'm having similar problems. Using hap-nodejs as a dependency, I've created my own module that does something similar to what BridgedCore.js does. Even though I'm not utilizing node-persist directly in my module, I have to include it and initialize the storage. I'm forced to call `storage.initSync();` to support something internal to the way hap-nodejs works... which is strange, but even more frustrating now I'm dealing with this dependency install-order issue.

```javascript
var storage = require('node-persist');
const HAP = require('hap-nodejs');
var uuid = HAP.uuid;
var Bridge = HAP.Bridge;
var Accessory = HAP.Accessory;
var Service = HAP.Service;
var Characteristic = HAP.Characteristic;

storage.initSync();

class HomekitBridge extends Bridge {

  constructor(name, relayController) {
    super(name, uuid.generate(name));
    this.relayController = relayController;
  }

  addValves(valves) {
    for (var key in valves) {
      this.addValve(key);
    }
  }

  addValve(name) {
    this.addBridgedAccessory(this._toAccessory(name));
  }

  _toAccessory(name) {
    var id = uuid.generate('underbluewaters:irrigation:'+name);
    let valve = new Accessory('Irrigation Valve', id);
    valve
      .getService(Service.AccessoryInformation)
      .setCharacteristic(Characteristic.Manufacturer, "Hunter")
      .setCharacteristic(Characteristic.Model, "606800")

    valve.on('identify', function(paired, callback) {
      callback(); // success
    });


    let self = this;

    valve
      .addService(Service.Outlet, name)
      .getCharacteristic(Characteristic.On)
      .on('set', function(value, callback) {
        self.relayController.set(name, value);
        callback();
      });

    valve
      .getService(Service.Outlet)
      .getCharacteristic(Characteristic.On)
      .on('get', function(callback) {
        var on = self.relayController.getState(name);
        callback(null, on);
      });

    valve
      .getService(Service.Outlet)
      .getCharacteristic(Characteristic.OutletInUse)
      .on('get', function(callback) {
        callback(null, true);
      });

    return valve;
  }

}

module.exports = HomekitBridge;
```

**Comment by underbluewaters** [comment]
Okay, found a solution to the problem with node-persist initialization. For me at least. I was able to call the init method exposed by the main hap-nodejs module and that solved the issue. So in my code, it looks like this:
```javascript
// no need for this
// const storage = require('node-persist');
// storage.initSync();
const HAP = require('hap-nodejs');
HAP.init();
```
