### ISSUE TITLE
Error when querying Siri about Garage Status

### ISSUE THREAD

**Issue by legotheboss** [KhaosT/HAP-NodeJS#259]
Hi everyone, 

I am having an issue when I ask Siri if the garage door is open. This causes this error to be displayed.

```
/home/pi/HAP-NodeJS/lib/util/once.js:11
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
      ^

Error: This callback function has already been called by someone else; it can only be called one time.
    at /home/pi/HAP-NodeJS/lib/util/once.js:11:13
    at null.<anonymous> (/home/pi/HAP-NodeJS/accessories/GarageDoorOpener_accessory.js:153:11)
    at emitTwo (events.js:92:20)
    at emit (events.js:172:7)
    at Characteristic.getValue (/home/pi/HAP-NodeJS/lib/Characteristic.js:120:10)
    at Bridge.<anonymous> (/home/pi/HAP-NodeJS/lib/Accessory.js:604:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/home/pi/HAP-NodeJS/lib/Accessory.js:568:8)
    at emitThree (events.js:97:13)
    at HAPServer.emit (events.js:175:7)
```

What is the solution to fix this?

**Comment by TheNoim** [comment]
Maybe it would help to post some of your code.

**Comment by legotheboss** [comment]
Solved it, an issue with my code.
