### ISSUE TITLE
Cannot find module 'curve25519-n'

### ISSUE THREAD

**Issue by Chris2L** [KhaosT/HAP-NodeJS#297]
Hi guys

Just did a git pull of the project and I'm now getting this error after calling sudo node Core.js:
module.js:339
    throw err;
    ^

Error: Cannot find module 'curve25519-n'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (HAP-NodeJS/lib/util/encryption.js:3:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

Am I doing something wrong or is there an issue in head?

**Comment by smith288** [comment]
Did you npm install?

**Comment by Chris2L** [comment]
Sorry, did the initial setup about 5 months ago and forgot to rerun npm install.  For the last few weeks I only tweaked my accessory and never needed npm install again.

Rookie move!  Thanx for the quick feedback @smith288
