### ISSUE TITLE
TypeError: Cannot read property

### ISSUE THREAD

**Issue by madcat-nl** [KhaosT/HAP-NodeJS#320]
Hi,

I just configured a new raspberry pi 3 and would like to also run Hap-nodeJS on this one, but i get an error which i do not really understand.
this is the error i'm receiving when starting up:

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
/home/pi/Hap/HAP-NodeJS/lib/model/IdentifierCache.js:37
  var value = this._cache[key];
                         ^
TypeError: Cannot read property 'a1fafdd1-bad1-4d6b-98f6-a2b76a15adcf|nextIID' of undefined
    at IdentifierCache.getCache (/home/pi/Hap/HAP-NodeJS/lib/model/IdentifierCache.js:37:26)
    at IdentifierCache.getIID (/home/pi/Hap/HAP-NodeJS/lib/model/IdentifierCache.js:73:8)
    at Characteristic._assignID (/home/pi/Hap/HAP-NodeJS/lib/Characteristic.js:220:30)
    at Service._assignIDs (/home/pi/Hap/HAP-NodeJS/lib/Service.js:188:20)
    at Bridge.Accessory._assignIDs (/home/pi/Hap/HAP-NodeJS/lib/Accessory.js:364:13)
    at Bridge.Accessory.publish (/home/pi/Hap/HAP-NodeJS/lib/Accessory.js:456:8)
    at Object.<anonymous> (/home/pi/Hap/HAP-NodeJS/BridgedCore.js:40:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

on BridgedCore.js line 40 the username of the bride is specified:
// Publish the Bridge on the local network.
bridge.publish({
  username: "CC:22:3D:E3:CE:F6",
  port: 51826,
  pincode: "314-00-002",
  category: Accessory.Categories.BRIDGE
});

Is it not able to persist this data on the sd card due to write permissions?

**Comment by madcat-nl** [comment]
i "solved" it by using a backup from another pi.

still not sure what was the actual issue
