### ISSUE TITLE
Reserved word errors

### ISSUE THREAD

**Issue by shokk** [KhaosT/HAP-NodeJS#341]
I'm seeing a few reserved word errors in hap-nodejs when running from homebridge:

/root/Downloads/homebridge/node_modules/hap-nodejs/lib/Camera.js:28
  let options = {
  ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/Downloads/homebridge/node_modules/hap-nodejs/index.js:3:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

and when running directly. Are these known issues?

# node BridgedCore.js --harmony
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

/root/Downloads/homebridge/node_modules/hap-nodejs/lib/camera/RTPProxy.js:6
class RTPProxy extends EventEmitter {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/Downloads/homebridge/node_modules/hap-nodejs/lib/StreamController.js:13:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

# node Core.js --harmony
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

/root/Downloads/homebridge/node_modules/hap-nodejs/lib/camera/RTPProxy.js:6
class RTPProxy extends EventEmitter {
^^^^^
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/Downloads/homebridge/node_modules/hap-nodejs/lib/StreamController.js:13:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by shokk** [comment]
OS is CentOS 6.8

**Comment by KhaosT** [comment]
IP Camera support requires nodejs v5.0 or later.

**Comment by shokk** [comment]
Thx. I'm assuming this is waaaaaaay too old for what I need.

# rpm -qa | grep nodejs | sort
nodejs-0.10.46-1.el6.x86_64

**Comment by shokk** [comment]
Barring that, is there any way to disable the camera support for now so that the service can run?

**Comment by KhaosT** [comment]
I'm afraid not...

**Comment by shokk** [comment]
Yes installing latest node from git and then using 
"n stable" to use 7.0.0 let it compile and run without error. Thanks!
