### ISSUE TITLE
Cannot read property

### ISSUE THREAD

**Issue by OczkoSX** [KhaosT/HAP-NodeJS#342]
Hi. What can be done about this?

```
/home/pi/HAP-NodeJS/lib/model/IdentifierCache.js:37
  var value = this._cache[key];
                         ^

TypeError: Cannot read property '2a41aea7-1145-49aa-961f-7243b30460e7|nextIID' of undefined
    at IdentifierCache.getCache (/home/pi/HAP-NodeJS/lib/model/IdentifierCache.js:37:26)
    at IdentifierCache.getIID (/home/pi/HAP-NodeJS/lib/model/IdentifierCache.js:73:8)
    at Characteristic._assignID (/home/pi/HAP-NodeJS/lib/Characteristic.js:220:30)
    at Service._assignIDs (/home/pi/HAP-NodeJS/lib/Service.js:189:20)
    at Accessory._assignIDs (/home/pi/HAP-NodeJS/lib/Accessory.js:364:13)
    at Accessory.publish (/home/pi/HAP-NodeJS/lib/Accessory.js:456:8)
    at /home/pi/HAP-NodeJS/Core.js:32:13
    at Array.forEach (native)
    at Object.<anonymous> (/home/pi/HAP-NodeJS/Core.js:20:13)
    at Module._compile (module.js:435:26)
```

**Comment by OczkoSX** [comment]
I use a fresh install of raspbian on RPi B

**Comment by OczkoSX** [comment]
Its the newest code from github, fresh install of raspbian

**Comment by KhaosT** [comment]
Please try to remove persist folder under ~/.homebridge

It looks like the persistent data is corrupted

**Comment by OczkoSX** [comment]
I don't use home bridge module. 
`-bash: /home/pi/.homebridge: No such file or directory`

Used this to install: https://gist.github.com/elvisimprsntr/f23c76587d48be0ec4b9

**Comment by legotheboss** [comment]
run this command

`sudo rm -rf /home/pi/HAP-NodeJS/persist`

**Comment by OczkoSX** [comment]
Still the same.
http://imgur.com/CrlFpM9
http://imgur.com/N2eWHdg

**Comment by legotheboss** [comment]
@OczkoSX So the error does not come up when you use BridgedCore.js?

**Comment by OczkoSX** [comment]
Both are not working, take a look at screenshot

**Comment by OczkoSX** [comment]
Anyone? I tried installing raspbian for second time - same result

**Comment by legotheboss** [comment]
Did you add any new accessory files?

**Comment by OczkoSX** [comment]
Nope. Clean install. Did not change anything. I'll try to remove all accessories

**Comment by OczkoSX** [comment]
Still the same

**Comment by OczkoSX** [comment]
After installing DietPi, everything works. Strange..
