### ISSUE TITLE
Do not start DEBUG = * node Core.js

### ISSUE THREAD

**Issue by Ramzes177** [KhaosT/HAP-NodeJS#447]
Hi at startup DEBUG = * node Core.js crashes with an error

/home/cubie/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: unknown
    at Error (native)
    at new Advertisement (/home/cubie/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/home/cubie/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/home/cubie/HAP-NodeJS/lib/Advertiser.js:43:30)
    at Accessory._onListening (/home/cubie/HAP-NodeJS/lib/Accessory.js:498:20)
    at emitNone (events.js:67:13)
    at HAPServer.emit (events.js:166:7)
    at HAPServer._onListening (/home/cubie/HAP-NodeJS/lib/HAPServer.js:169:8)
    at emitNone (events.js:67:13)
    at EventedHTTPServer.emit (events.js:166:7)

Help me to understand

**Comment by KhaosT** [comment]
What are you doing with `DEBUG=* node Core.jsDEBUG=* node Core.js` ???
If you want to run with debug level of logging, just do it once... `DEBUG=* node Core.js`

**Comment by Ramzes177** [comment]
It accidentally executed such a command
This error when starting DEBUG = * node Core.js
