### ISSUE TITLE
Not able to start server

### ISSUE THREAD

**Issue by samiramin** [KhaosT/HAP-NodeJS#45]
I have installed nodejs 0.10.36 in Mac 10.10.0

Rebuild it
and tried to run like
node Core.js

I am getting this error. its not able to start.
Can you pls check whats the issue ?

----------------------------------------------------------------------------------------------------------------
module.js:340
    throw err;
          ^
Error: Cannot find module './build/Release/curve'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Sam/Documents/Homekit/Server/HAP-NodeJS-master/node_modules/curve25519/index.js:1:77)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by KhaosT** [comment]
@samiramin Did you do "npm rebuild" before running the program?

**Comment by samiramin** [comment]
yes, i did it.
I exited when it displayed 
> node-gyp rebuild

It was doing nothing just stoped there. so i exited and thn try to build
--------------------------------------
Sam-Mac-6:HAP-NodeJS-master Sam$ npm rebuild

> curve25519@1.0.0 install /Users/Sam/Documents/Homekit/Server/HAP-NodeJS-master/node_modules/curve25519
> node-gyp rebuild

^Z

**Comment by KhaosT** [comment]
@samiramin for the first time it may takes a while... please wait until it finishes.
