### ISSUE TITLE
Error: Symbol ed25519_module not found

### ISSUE THREAD

**Issue by johngson** [KhaosT/HAP-NodeJS#57]
Hi, it's not possible for me to start HAP-NodeJS. This is my setup:

$ npm -v
1.4.28
$ node -v
v0.10.36

 I've followed the instructions but got the following error:

$ node BridgedCore.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

/home/pi/HAP-NodeJS/node_modules/ed25519/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Symbol ed25519_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/pi/HAP-NodeJS/node_modules/ed25519/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/pi/HAP-NodeJS/node_modules/ed25519/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Any idea?

**Comment by KhaosT** [comment]
@johngson Please use node.js 0.12.x. For some reasons, ed25519 doesn't work in 0.10.x
