### ISSUE TITLE
User/Pass error

### ISSUE THREAD

**Issue by HugoTheBoss** [KhaosT/HAP-NodeJS#60]
Hi KhaosT,

when i try to pair with a device i get the following error:

Start Pair M3

/home/pi/homebridge/node_modules/srp/lib/srp.js:393
      throw new Error("client did not use the same password");
            ^
Error: client did not use the same password
    at Object.checkM1 (/home/pi/homebridge/node_modules/srp/lib/srp.js:393:13)
    at Object.processPairStepTwo (/home/pi/homebridge/lib/HAP-NodeJS/Server.js:273:18)
    at Object.processPairSequence (/home/pi/homebridge/lib/HAP-NodeJS/Server.js:233:11)
    at IncomingMessage.<anonymous> (/home/pi/homebridge/lib/HAP-NodeJS/Server.js:38:17)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:765:14)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)

any ideas?

**Comment by KhaosT** [comment]
Please make sure you entered the right pin code on iOS side.

**Comment by HugoTheBoss** [comment]
I´ve entered the right PIN Code! 031-45-154
Tryed with different accessories many times

**Comment by KhaosT** [comment]
@HugoTheBoss That's strange, can you try to remove ./persist and try again?

**Comment by HugoTheBoss** [comment]
i did allready, also reset the homekit-data on ios

**Comment by KhaosT** [comment]
That's really weird ... Can you post the full log from start to exception?

**Comment by HugoTheBoss** [comment]
I´m not at home right now... will post you the log in the afternoon!

**Comment by HugoTheBoss** [comment]
I've reinstalled everything about 4 times, and now it seems to work?!
