### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by arim215** [KhaosT/HAP-NodeJS#615]
Getting this error when trying to run a python file from the .js accessory...

npm version : 2.14.7
node : v4.2.1
python-shell@1.0.6

`HAP-NodeJS starting...
/home/pi/HAP-NodeJS/node_modules/python-shell/index.js:28
function extend(obj, ...args) {
                                  ^^^ (under the "...args")

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/HAP-NodeJS/accessories/AmbianceLights_accessory.js:1:74)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)`

My code : 
`const ps = require('python-shell')
var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var err = null; // in case there were any problems

// here's a fake hardware device that we'll expose to HomeKit
var FAKE_OUTLET = {
    setPowerOn: function(on) {
    console.log("Turning the light %s!...", on ? "on" : "off");
    if (on) {
          FAKE_OUTLET.powerOn = true;
          ps.PythonShell.run('AM_on.py', function (err) {
                                console.log('On Success');});
    } else {
          FAKE_OUTLET.powerOn = false;
          ps.PythonShell.run('AM_off.py', function (err) {
                                console.log('On Success');});
    }
  },
    identify: function() {
    console.log("Identify the light.");
    }
}
`

**Comment by Apollon77** [comment]
Node 4 is end of life, npm 2.x veeery old too. You should update your Environment.
