### ISSUE TITLE
Install on debian

### ISSUE THREAD

**Issue by tocks53** [KhaosT/HAP-NodeJS#73]
On the npm install, i have this error :

root@debian:~# git clone https://github.com/KhaosT/HAP-NodeJS.git
Cloning into 'HAP-NodeJS'...
remote: Counting objects: 1498, done.
Receiving objects: 100% (1498/1498), 4.14 MiB | 987 KiB/s, done.
remote: Total 1498 (delta 0), reused 0 (delta 0), pack-reused 1498
Resolving deltas: 100% (419/419), done.
root@debian:~# cd HAP-NodeJS/œ
-bash: cd: HAP-NodeJS/œ: Aucun fichier ou dossier de ce type
root@debian:~# cd HAP-NodeJS/
root@debian:~/HAP-NodeJS# npm install
-
> curve25519@1.0.0 install /root/HAP-NodeJS/node_modules/curve25519
> node-gyp rebuild

make: entrant dans le répertoire « /root/HAP-NodeJS/node_modules/curve25519/build »
  CXX(target) Release/obj.target/curve/node_curve.o
  SOLINK_MODULE(target) Release/obj.target/curve.node
  SOLINK_MODULE(target) Release/obj.target/curve.node: Finished
  COPY Release/curve.node
make: quittant le répertoire « /root/HAP-NodeJS/node_modules/curve25519/build »

> ed25519@0.0.2 install /root/HAP-NodeJS/node_modules/ed25519
> node-gyp rebuild

make: entrant dans le répertoire « /root/HAP-NodeJS/node_modules/ed25519/build »
  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sign.o
  CC(target) Release/obj.target/ed25519/src/ed25519/open.o
  CC(target) Release/obj.target/ed25519/src/ed25519/crypto_verify_32.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_double_scalarmult.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_scalarmult_base.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_precomp_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_cached.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_madd.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_msub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p3.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_1.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_cmov.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_copy.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_neg.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_mul.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_invert.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnegative.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnonzero.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_pow22523.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_reduce.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_muladd.o
  CXX(target) Release/obj.target/ed25519/src/ed25519.o
  SOLINK_MODULE(target) Release/obj.target/ed25519.node
  SOLINK_MODULE(target) Release/obj.target/ed25519.node: Finished
  COPY Release/ed25519.node
make: quittant le répertoire « /root/HAP-NodeJS/node_modules/ed25519/build »

> bignum@0.9.2 install /root/HAP-NodeJS/node_modules/srp/node_modules/bignum
> node-gyp configure build

make: entrant dans le répertoire « /root/HAP-NodeJS/node_modules/srp/node_modules/bignum/build »
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  SOLINK_MODULE(target) Release/obj.target/bignum.node: Finished
  COPY Release/bignum.node
make: quittant le répertoire « /root/HAP-NodeJS/node_modules/srp/node_modules/bignum/build »

> mdns@2.2.9 install /root/HAP-NodeJS/node_modules/mdns
> node-gyp rebuild

make: entrant dans le répertoire « /root/HAP-NodeJS/node_modules/mdns/build »
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: Aucun fichier ou dossier de ce type
compilation terminated.
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Erreur 1
make: quittant le répertoire « /root/HAP-NodeJS/node_modules/mdns/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/opt/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/HAP-NodeJS/node_modules/mdns
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/opt/node/bin/node" "/opt/node/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/HAP-NodeJS/npm-debug.log

**Comment by tocks53** [comment]
soory, i solved mys issue.
npm install <module name>

sorry you can close this isue
