### ISSUE TITLE
Cannot find module 'path'

### ISSUE THREAD

**Issue by codyc1515** [KhaosT/HAP-NodeJS#750]
When running the command `sudo DEBUG=* ts-node --files src/Core.ts` I receive the messages below. Installing path in the local folder fulfils the dependencies, but should this not be done automatically?

```
/usr/lib/node_modules/ts-node/src/index.ts:245
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/Core.ts:1:18 - error TS2307: Cannot find module 'path'.

1 import path from 'path';
                   ~~~~~~
src/Core.ts:7:1 - error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the `lib` compiler option to include 'dom'.

7 console.log("HAP-NodeJS starting...");
  ~~~~~~~
src/Core.ts:16:21 - error TS2304: Cannot find name '__dirname'.

16 var dir = path.join(__dirname, "accessories");
                       ~~~~~~~~~
src/Core.ts:47:3 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

47   process.on(signal, () => {
     ~~~~~~~
src/Core.ts:52:5 - error TS2304: Cannot find name 'setTimeout'.

52     setTimeout(() => {
       ~~~~~~~~~~
src/Core.ts:53:9 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node`.

53         process.exit(128 + signals[signal]);
           ~~~~~~~

    at createTSError (/usr/lib/node_modules/ts-node/src/index.ts:245:12)
    at reportTSError (/usr/lib/node_modules/ts-node/src/index.ts:249:19)
    at getOutput (/usr/lib/node_modules/ts-node/src/index.ts:357:34)
    at Object.compile (/usr/lib/node_modules/ts-node/src/index.ts:415:32)
    at Module.m._compile (/usr/lib/node_modules/ts-node/src/index.ts:493:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/lib/node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
```

**Comment by codyc1515** [comment]
There is also a dependency on simple-plist.

**Comment by codyc1515** [comment]
You have to run the command `node install`.
