### ISSUE TITLE
The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object

### ISSUE THREAD

**Issue by hassbian-ABC** [KhaosT/HAP-NodeJS#755]

**Comment by hassbian-ABC** [comment]
ypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:206:11)
    at Object.from (/root/HAP-NodeJS/node_modules/buffer-shims/index.js:53:19)
    at StreamController._handleSelectedStreamConfigurationWrite (/root/HAP-NodeJS/src/lib/StreamController.ts:402:27)
    at SelectedRTPStreamConfiguration.<anonymous> (/root/HAP-NodeJS/src/lib/StreamController.ts:384:14)
    at SelectedRTPStreamConfiguration.emit (events.js:189:13)
    at SelectedRTPStreamConfiguration.EventEmitter.emit (domain.js:441:20)
    at SelectedRTPStreamConfiguration.EventEmitter.emit (/root/HAP-NodeJS/src/lib/EventEmitter.ts:42:22)
    at SelectedRTPStreamConfiguration.Characteristic._this.setValue (/root/HAP-NodeJS/src/lib/Characteristic.ts:583:12)
    at /root/HAP-NodeJS/src/lib/Accessory.ts:1179:24
    at Array.forEach (<anonymous>)

**Comment by Supereg** [comment]
Could you describe what you are doing and when this error occurs?
Also it would be helpful if you could turn on debug mode by setting the `DEBUG=*` environment variable (refer to the README), so we can get an idea what value is being set on the SelectedRTPStreamConfiguration characteristic.
Also what accessory are you using exactly?
Are you using any special things or is the accessory just simply paired with HomeKit?
