### ISSUE TITLE
MQTT Temperature Sensor - How convert a string to float?

### ISSUE THREAD

**Issue by TeraJaQ** [KhaosT/HAP-NodeJS#787]
i'm tring to create a Temperature senso accessory based on MQTT but i get this error whent try to start` ts-node --files src/Core.ts`

this is my accessory

```
var Temperature = 0.0;
// MQTT Setup
var mqtt = require('mqtt');
var options = {
  port: 1883,
  host: '192.168.1.123',
  clientId: 'ExternalTemperatureSensorTest'
};
var client = mqtt.connect(options);
client.on('connect', function () {
  client.subscribe('ExtTemp');
  client.publish('info','exttemperature');
});
client.on('message', function(topic:any, message:any) {
  if (topic == 'ExtTemp')
    Temperature = parseFloat(message);
});


// here's a fake temperature sensor device that we'll expose to HomeKit
import { Accessory, Categories, Characteristic, CharacteristicEventTypes, CharacteristicValue, NodeCallback, Service, uuid } from '..';

var TEMP_SENSOR = {
  currentTemperature: 50,
  
  getTemperature: function() {
		client.publish('info','exttemperature');
		TEMP_SENSOR.currentTemperature = (parseFloat(Temperature));
		return TEMP_SENSOR.currentTemperature;
  },
  randomizeTemperature: function() {
    TEMP_SENSOR.currentTemperature = parseFloat(Temperature);
  }
}


// Generate a consistent UUID for our Temperature Sensor Accessory that will remain the same
// even when restarting our server. We use the `uuid.generate` helper function to create
// a deterministic UUID based on an arbitrary "namespace" and the string "temperature-sensor".
var sensorUUID = uuid.generate('hap-nodejs:accessories:temperature-sensor');

// This is the Accessory that we'll return to HAP-NodeJS that represents our fake lock.
var sensor = exports.accessory = new Accessory('Temperature Sensor', sensorUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
// @ts-ignore
sensor.username = "C1:5D:3A:AE:5E:FF";
// @ts-ignore
sensor.pincode = "031-45-154";
// @ts-ignore
sensor.category = Categories.SENSOR;

// Add the actual TemperatureSensor Service.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKit.ts`
sensor
  .addService(Service.TemperatureSensor)!
  .getCharacteristic(Characteristic.CurrentTemperature)!
  .on(CharacteristicEventTypes.GET, (callback: NodeCallback<CharacteristicValue>) => {

    // return our current value
    callback(null, TEMP_SENSOR.getTemperature());
  });

// randomize our temperature reading every 3 seconds
setInterval(function() {
  TEMP_SENSOR.getTemperature();
  TEMP_SENSOR.randomizeTemperature();

  // update the characteristic value so interested iOS devices can get notified
  sensor
    .getService(Service.TemperatureSensor)!
    .setCharacteristic(Characteristic.CurrentTemperature, TEMP_SENSOR.currentTemperature);

}, 3000);

```

and this is the error

```
HAP-NodeJS starting...

/usr/local/lib/node_modules/ts-node/src/index.ts:421
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/accessories/ExternalTemperature_accessory.ts:27:50 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

27     TEMP_SENSOR.currentTemperature = (parseFloat(Temperature));
                                                    ~~~~~~~~~~~
src/accessories/ExternalTemperature_accessory.ts:34:49 - error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.

34     TEMP_SENSOR.currentTemperature = parseFloat(Temperature);
                                                   ~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:421:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:425:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:530:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:735:32)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:814:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:817:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
```

**Comment by TeraJaQ** [comment]
I've solved... this is my Temperature and Humidity sensor over MQTT

```
var Temperature = 0.0;
var Humidity = 0;
// MQTT Setup
var mqtt = require('mqtt');
var options = {
  port: 1883,
  host: '192.168.1.123',
  clientId: 'TemperatureHumiditySensorTest'
};
var client = mqtt.connect(options);
client.on('connect', function () {
  client.subscribe('HOME/Current/#');
  client.publish('HOME/get/Temperature','???');
  client.publish('HOME/get/Humidity','???');
});
client.on('message', function(topic:any, message:any) {
  if (topic == 'HOME/Current/Temperature')
    Temperature = parseFloat(message);
  if (topic == 'HOME/Current/Humidity')
    Humidity = parseFloat(message);
});

// here's a temperature an humidity sensor device that we'll expose to HomeKit
import {
 Accessory,
 Categories,
 Characteristic,
 CharacteristicEventTypes,
 CharacteristicValue,
 NodeCallback,
 Service,
 uuid }
 from '..';

var TEMP_SENSOR = {
  currentTemperature: Temperature,
  currentHumidity: Humidity,

  getTemperature: function() {
   client.publish('HOME/get/Temperature','???');
   TEMP_SENSOR.currentTemperature = Temperature;
   //console.log("Getting the current temperature!");
   return TEMP_SENSOR.currentTemperature;
  },

   getHumidity: function() { 
    client.publish('HOME/get/Humidity','???');
    TEMP_SENSOR.currentHumidity = Humidity;
    //console.log("Getting the current humidity!");
    return TEMP_SENSOR.currentHumidity;
  },

  setTempHum: function() {
    TEMP_SENSOR.currentTemperature = Temperature;
    TEMP_SENSOR.currentHumidity = Humidity;
  }
}


// Generate a consistent UUID for our Temperature Sensor Accessory that will remain the same
// even when restarting our server. We use the `uuid.generate` helper function to create
// a deterministic UUID based on an arbitrary "namespace" and the string "temperature-sensor".
var sensorUUID = uuid.generate('hap-nodejs:accessories:temperature-sensor');

// This is the Accessory that we'll return to HAP-NodeJS that represents our fake lock.
var sensor = exports.accessory = new Accessory('Temperature Sensor', sensorUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
// @ts-ignore
sensor.username = "C1:5D:3A:AE:5E:FF";
// @ts-ignore
sensor.pincode = "031-45-154";
// @ts-ignore
sensor.category = Categories.SENSOR;

// Add the actual TemperatureSensor Service.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKit.ts`



sensor
  .addService(Service.TemperatureSensor, "Temperatura")!
  .getCharacteristic(Characteristic.CurrentTemperature)!
  .on(CharacteristicEventTypes.GET, (callback: NodeCallback<CharacteristicValue>) => {
    // return our current value
    callback(null, TEMP_SENSOR.getTemperature());
  });
sensor
  .addService(Service.HumiditySensor, "Umidità")!
  .getCharacteristic(Characteristic.CurrentRelativeHumidity)!
  .on(CharacteristicEventTypes.GET, (callback: NodeCallback<CharacteristicValue>) => {
    callback(null, TEMP_SENSOR.getHumidity());
});


sensor
  .getService(Service.AccessoryInformation)!
  .setCharacteristic(Characteristic.Manufacturer, "Jacques Fargion")
  .setCharacteristic(Characteristic.Model, "DHT22 Temperature Humidity sensor")
  .setCharacteristic(Characteristic.SerialNumber, "AA-1234");

// update our temperature and humidity reading every 30 seconds
setInterval(function() {
  TEMP_SENSOR.getTemperature();
  TEMP_SENSOR.getHumidity();
  TEMP_SENSOR.setTempHum();

  // update the characteristic value so interested iOS devices can get notified
  sensor
    .getService(Service.TemperatureSensor)!
    .setCharacteristic(Characteristic.CurrentTemperature, TEMP_SENSOR.currentTemperature);
  sensor
    .getService(Service.HumiditySensor)!
    .setCharacteristic(Characteristic.CurrentRelativeHumidity, TEMP_SENSOR.currentHumidity);
}, 30000);
```
