### ISSUE TITLE
Program won't start

### ISSUE THREAD

**Issue by emptygalaxy** [KhaosT/HAP-NodeJS#79]
I'm running on a mac here using node v0.12.5 and I can't get the program to start.
Here's my output:

$ node BridgedCore.js 
/Users/xxxx/HAP-NodeJS-master/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
          ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/xxxxx/HAP-NodeJS-master/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by beckmx** [comment]
this is because you used sudo, try this
npm rebuild
rm -rf node_modules
npm i

**Comment by nzhome** [comment]
@emptygalaxy did beckmx's suggestion fix it?

**Comment by beckmx** [comment]
yes it did (well I had the same problem and it fixed the issue)

**Comment by nzhome** [comment]
thanks. please press the close issue button.  cheers.
