### ISSUE TITLE
hap-nodeJS keeps on crashing

### ISSUE THREAD

**Issue by SoundGuy** [KhaosT/HAP-NodeJS#805]
I've been using this for over  year now, slowly adding more devices and accessories over JS. 
I'm using an RPI 1 that also is running an MQTT broker.  I've recently also added another RPI3 with a hass.io and a few new accessories. 

Since last week, i've been getting a lot of these crashes in a loop in the Core.js proccess making it boot over and over again and not really functioning.

any ideas what's causing this and how to fix it?

events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Connection refused: undefined
    at MqttClient._handleConnack (/home/pi/HAP-NodeJS/node_modules/mqtt/lib/client.js:877:15)
    at MqttClient._handlePacket (/home/pi/HAP-NodeJS/node_modules/mqtt/lib/client.js:319:12)
    at work (/home/pi/HAP-NodeJS/node_modules/mqtt/lib/client.js:261:12)
    at Writable.writable._write (/home/pi/HAP-NodeJS/node_modules/mqtt/lib/client.js:271:5)
    at doWrite (/home/pi/HAP-NodeJS/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/pi/HAP-NodeJS/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Writable.write (/home/pi/HAP-NodeJS/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:557:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
error: Forever detected script exited with code: 1
error: Script restart attempt #1882

**Comment by Supereg** [comment]
This has nothing to do with HAP-NodeJS.
Your MQTT client seems to not be able to connect to your broker. And your code seems to be handling such errors and thus the application just crashes.

**Comment by SoundGuy** [comment]
any ideas how do i workaround this issue?

**Comment by SoundGuy** [comment]
like, Is  it in one of the accessories code that i need to handle?

**Comment by Supereg** [comment]
> any ideas how do i workaround this issue?

I don't, as I don't know your code/accessory.

**Comment by SoundGuy** [comment]
ok thanks.for future reference for anyone gogoleing this - i added this code in all my accessories:

client.on('error', function (err) {
    console.log(err);
});
client.on('connect', function () {
    console.log('I am connected!');
});

thanks for pointing me to the right direction.
